{
  "language": "python",
  "python": "2.7",
  "install": [
    "pip install -r requirements.txt",
    "pip install codecov",
    "pip install pytest-cov"
  ],
  "addons": [
    "apt": [
      "packages": [
        "python-requests",
        "python-coverage",
        "python-mock",
        "python-dev",
        "libmysqlclient-dev"
      ]
    ]
  ],
  "services": [
    "postresql"
  ],
  "before_install": [
    "psql -c 'create database travis_ci_test;' -U postgres"
  ],
  "script": [
    "coverage run main.py migrate",
    "coverage run main.py seed",
    "coverage run main.py run"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux",
  "after_success": [
    "codecov"
  ]
}
